- name: variables from multi level
  hosts: local
  connection: local

  vars:
    course: Devops
    trainer: Sivakumar
    duration: 4 months
  
  tasks:
  - name: printing course info
    ansible.builtin.debug:
    msg: course info {{ course }} {{ duration }} {{ trainer }}

  - name: printing course info again
    ansible.builtin.debug:
    msg: course info {{ course }} {{ duration }} {{ trainer }}

