- name: variables from different file
  hosts: localhost
  connection: local

  vars_files:
    - course.yaml
  
  tasks:
  - name: variable from course.yaml file
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

