- name: variables from different file
  hosts: local
  connection: local

  tasks:
  - name: variables from file global
    vars:
      course: AWS
      trainer: Sivakumar
      duration: "1months"
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

  - name: variable from course.yaml file
    vars_files:
     course.yaml
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

