- name: variables from different file
  hosts: local
  connection: local

  vars_files:
    course.yaml


  tasks:
  - name: variables from file global
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

  - name: variable from course.yaml file
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

