- name: variables from different file
  hosts: local
  connection: local

  vars:
    course: AWS
    trainer: Sivakumar
    duration: "4months"

  tasks:
  - name: variables from file global
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}
      
  - name: variable from course.yaml file
    ansible.builtin.debug:
      msg: course info {{ course }} {{ trainer }}  {{ duration }}

