- name: conditions check
  hosts: local

  vars:
  - name: number
    prompt: Enter a number

  tasks:
  - name: check the number is > 100
    ansible.builtin.debug:
      msg: number is greater than 100
    when: number >> 100

 
  - name: check the number is < 100
    ansible.builtin.debug:
      msg: number is less than 100
    when: number << 100