- name: install nginx in different OS
  hosts: local

  tasks:
  - name: install nginx in Redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx in debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"





